import React,{useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Eye,EyeOff,ShieldCheck,CheckCircle2} from 'lucide-react';
import './auth.css';
export default function AuthPage(){
 const [mode,setMode]=useState(location.pathname==='/register'?'register':'login'),[form,setForm]=useState({name:'',email:'',password:''}),[show,setShow]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false),[user,setUser]=useState(null),[ready,setReady]=useState(false);
 useEffect(()=>{let active=true;fetch('/api/v1/auth/me',{credentials:'same-origin',cache:'no-store'}).then(async r=>r.ok?(await r.json()).user:null).then(v=>{if(active)setUser(v)}).catch(()=>{}).finally(()=>{if(active)setReady(true)});return()=>{active=false}},[]);
 const change=next=>{setMode(next);setError('');history.replaceState({},'',next==='register'?'/register':'/login')};
 const submit=async e=>{e.preventDefault();setError('');setLoading(true);try{const body={email:form.email.trim(),password:form.password,...(mode==='register'?{name:form.name.trim()}:{})};const r=await fetch('/api/v1/auth/'+(mode==='register'?'register':'login'),{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Sign in failed.');if(!data.user)throw Error('Sign in was not completed.');window.location.assign('/')}catch(e){setError(e.message)}finally{setLoading(false)}};
 return <div className="lv-auth-page"><header className="lv-auth-brand"><a href="/">✳ &nbsp; lifevault</a><small>A home for all of you.</small></header><div className="lv-auth-layout">
 <aside className="lv-auth-art"><div className="lv-auth-meta">YOUR STORY, YOUR SPACE <span>— LIFEVAULT</span></div><div className="lv-auth-object"><div className="lv-auth-arch back"/><div className="lv-auth-arch front">THE STORIES THAT<br/>MAKE US, US.<span>✳</span></div></div><div><h1>Keep what matters.<br/><em>Return to it anytime.</em></h1><p>Memories, milestones, little moments, and everything you create. Collected thoughtfully in one place.</p></div><small>PERSONAL BY NATURE &nbsp; · &nbsp; MADE TO LAST</small></aside>
 <main className="lv-auth-panel"><div className="lv-auth-inner"><a className="lv-auth-back" href="/"><ArrowLeft size={16}/> Back to LifeVault</a>{ready&&user?<><CheckCircle2 color="#527865"/><h2>You're signed in.</h2><p>Welcome back, {user.name}.</p><a className="lv-auth-submit" href="/">Open LifeVault <ArrowRight size={17}/></a></>:<>
 <div className="lv-auth-eyebrow">{mode==='login'?'WELCOME BACK':'CREATE YOUR ACCOUNT'}</div><h2>{mode==='login'?'A space for your stories.':'Start your next chapter.'}</h2><p className="lv-auth-lead">{mode==='login'?'Sign in to your LifeVault account.':'Create your own LifeVault account.'} Your existing memories remain saved in this browser until cloud sync is available.</p>
 <div className="lv-auth-modes"><button className={mode==='login'?'active':''} onClick={()=>change('login')}>Sign in</button><button className={mode==='register'?'active':''} onClick={()=>change('register')}>Create account</button></div>
 <form className="lv-auth-form" onSubmit={submit}>{mode==='register'&&<label>Your name<input autoComplete="name" required maxLength="80" placeholder="What should we call you?" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Email address<input required type="email" autoComplete="email" maxLength="254" placeholder="you@example.com" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>
 <label>Password<div className="lv-auth-password"><input required type={show?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='register'?12:1} maxLength="128" placeholder={mode==='register'?'At least 12 characters':'Your password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" onClick={()=>setShow(!show)} aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>
 {mode==='register'&&<small>Use a unique password with at least 12 characters.</small>}{error&&<p className="lv-auth-error" role="alert">{error}</p>}<button className="lv-auth-submit" disabled={loading}>{loading?'Working…':mode==='login'?'Sign in':'Create account'} <ArrowRight size={17}/></button></form>
 <div className="lv-auth-note"><ShieldCheck size={19}/><p>Secure server-side account sessions. Personal memories and photos still remain on your device; account-based cloud synchronization, email verification, and password reset are coming later.</p></div></>}</div></main></div><footer className="lv-auth-footer">LifeVault © 2026 <span>Keep the moments. Make room for more.</span></footer></div>;
}