import React,{useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Eye,EyeOff,ShieldCheck,CheckCircle2} from 'lucide-react';
import './auth.css';
import {portraitData} from './portrait.js';
export default function AuthPage({serverError=''}){
 const [mode,setMode]=useState(location.pathname==='/register'?'register':'login'),[form,setForm]=useState({name:'',email:'',password:''}),[avatar,setAvatar]=useState(''),[avatarBusy,setAvatarBusy]=useState(false),[show,setShow]=useState(false),[confirmPassword,setConfirmPassword]=useState(''),[capsLock,setCapsLock]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false),[user,setUser]=useState(null),[ready,setReady]=useState(false);
 useEffect(()=>{let active=true;fetch('/api/v1/auth/me',{credentials:'same-origin',cache:'no-store'}).then(async r=>r.ok?(await r.json()).user:null).then(v=>{if(active)setUser(v)}).catch(()=>{}).finally(()=>{if(active)setReady(true)});return()=>{active=false}},[]);
 const change=next=>{setMode(next);setError('');setForm({name:'',email:'',password:''});setConfirmPassword('');setAvatar('');setShow(false);history.replaceState({},'',next==='register'?'/register':'/login')};
 const nameOk=/^[\p{L}][\p{L}\p{M}]*(?:[ '\u2019.-][\p{L}][\p{L}\p{M}]*)*$/u.test(form.name.trim())&&form.name.trim().length>=2&&form.name.trim().length<=60;
 const passwordOk=form.password.length>=12&&form.password.length<=128&&/\p{L}/u.test(form.password)&&/\p{N}/u.test(form.password)&&!/[\u0000-\u001f\u007f]/.test(form.password);
 const canSubmit=mode==='login'||(nameOk&&passwordOk&&confirmPassword===form.password&&!!avatar&&!avatarBusy);
 const submit=async e=>{e.preventDefault();setError('');if(!canSubmit){setError('Check your name, password strength and confirmation.');return}setLoading(true);try{const body={email:form.email.trim(),password:form.password,...(mode==='register'?{name:form.name.trim(),avatar}:{})};const r=await fetch('/api/v1/auth/'+(mode==='register'?'register':'login'),{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Sign in failed.');if(!data.user)throw Error('Sign in was not completed.');window.location.assign('/')}catch(e){setError(e.message)}finally{setLoading(false)}};
 return <div className="lv-auth-page"><header className="lv-auth-brand"><a href="/">✳ &nbsp; lifevault</a><small>A home for all of you.</small></header><div className="lv-auth-layout">
 <aside className="lv-auth-art"><div className="lv-auth-meta">YOUR STORY, YOUR SPACE <span>— LIFEVAULT</span></div><div className="lv-auth-object"><div className="lv-auth-arch back"/><div className="lv-auth-arch front">THE STORIES THAT<br/>MAKE US, US.<span>✳</span></div></div><div><h1>Keep what matters.<br/><em>Return to it anytime.</em></h1><p>Memories, milestones, little moments, and everything you create. Collected thoughtfully in one place.</p></div><small>PERSONAL BY NATURE &nbsp; · &nbsp; MADE TO LAST</small></aside>
 <main className="lv-auth-panel"><div className="lv-auth-inner"><div className="lv-auth-back"><ShieldCheck size={16}/> Your private space</div>{ready&&user?<><CheckCircle2 color="#527865"/><h2>You're signed in.</h2><p>Welcome back, {user.name}.</p><a className="lv-auth-submit" href="/">Open LifeVault <ArrowRight size={17}/></a></>:<>
 <div className="lv-auth-eyebrow">{mode==='login'?'WELCOME BACK':'CREATE YOUR ACCOUNT'}</div><h2>{mode==='login'?'A space for your stories.':'Start your next chapter.'}</h2><p className="lv-auth-lead">{mode==='login'?'Sign in to your LifeVault account.':'Create your own LifeVault account.'} Your personal space starts with a name and a picture. Device-only photos stay on this device.</p>
 <div className="lv-auth-modes"><button className={mode==='login'?'active':''} onClick={()=>change('login')}>Sign in</button><button className={mode==='register'?'active':''} onClick={()=>change('register')}>Create account</button></div>
 <form className="lv-auth-form" onSubmit={submit}>{mode==='register'&&<label className="lv-signup-picture"><span>Your profile picture <strong>Required</strong></span><span className="lv-picture-row"><span className="lv-picture-preview">{avatar?<img src={avatar} alt="Your selected profile picture"/>:<span aria-hidden="true">+</span>}</span><span><span className="lv-picture-action">{avatarBusy?'Preparing photo…':avatar?'Change picture':'Choose a picture'}</span><small>Your account is personal. A photo helps make it yours.</small></span></span><input type="file" accept="image/jpeg,image/png,image/webp" required={!avatar} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setAvatarBusy(true);setError('');try{setAvatar(await portraitData(file))}catch(err){setAvatar('');setError(err.message)}finally{setAvatarBusy(false)}}}/></label>}{mode==='register'&&<label>Your name<input autoComplete="name" required minLength="2" maxLength="60" placeholder="Your first and last name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} pattern="[A-Za-z][A-Za-z .'-]*" title="2–60 letters and name separators"/>{form.name&&!nameOk&&<span className="lv-auth-validation">Use 2–60 letters; spaces, hyphens and apostrophes are allowed.</span>}</label>}<label>Email address<input required type="email" autoComplete="email" maxLength="254" placeholder="you@example.com" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>
 <label>Password<div className="lv-auth-password"><input required type={show?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='register'?12:1} maxLength="128" onKeyUp={e=>setCapsLock(e.getModifierState('CapsLock'))} placeholder={mode==='register'?'At least 12 characters':'Your password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" onClick={()=>setShow(!show)} aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>
 {capsLock&&<small className="lv-auth-validation">Caps Lock is on.</small>}{mode==='register'&&<><small className={passwordOk?'lv-auth-good':'lv-auth-help'}>At least 12 characters, including letters and numbers. A unique passphrase is best.</small><label>Confirm password<input required type={show?'text':'password'} autoComplete="new-password" minLength="12" maxLength="128" placeholder="Re-enter your password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/>{confirmPassword&&confirmPassword!==form.password&&<span className="lv-auth-validation">Passwords must match.</span>}</label></>}{(error||serverError)&&<p className="lv-auth-error" role="alert">{error||serverError}</p>}<button className="lv-auth-submit" disabled={loading||!canSubmit}>{loading?'Working…':mode==='login'?'Sign in':'Create account'} <ArrowRight size={17}/></button></form>
 <div className="lv-auth-note"><ShieldCheck size={19}/><p>Secure server-side account sessions. Account-owned stories and memory pages synchronize to D1. Photos selected from this device stay here until cloud media storage is connected. Email verification and password recovery are not yet available.</p></div></>}</div></main></div><footer className="lv-auth-footer">LifeVault © 2026 <span>Keep the moments. Make room for more.</span></footer></div>;
}