import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{House,Compass,BriefcaseBusiness,FolderKanban,Trophy,GraduationCap,FileText,Layers3,Plus,Search,ArrowRight,ArrowUpRight,Lock,Globe,Menu,X,Sparkles,Settings,Trash2,Check,Eye,UserRound}from'lucide-react';
import './style.css';
const seed=[
{id:1,type:'Project',title:'POS Device Health Platform',description:'A project that turned complex signals into simple, actionable insights.',year:'2025',visibility:'Public'},
{id:2,type:'Education',title:'A new chapter in cybersecurity',description:'Learning, growing and creating a stronger foundation.',year:'2023',visibility:'Public'},
{id:3,type:'Achievement',title:'Trust-Aware AI Research',description:'Exploring thoughtful, human-guided applications of AI.',year:'2026',visibility:'Public'},
{id:4,type:'Experience',title:'Building software that matters',description:'From curiosity to real-world impact, one step at a time.',year:'2024',visibility:'Public'}];
const menu=[['Home',House],['My Journey',Compass],['Experience',BriefcaseBusiness],['Projects',FolderKanban],['Achievements',Trophy],['Education',GraduationCap],['Documents',FileText]];
const emoji={Project:'✦',Education:'🎓',Achievement:'🏆',Experience:'💼',Document:'📄'};
const lookup={Projects:'Project',Achievements:'Achievement',Experience:'Experience',Education:'Education',Documents:'Document'};
function stored(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
function App(){
const[page,setPage]=useState('Home'),[items,setItems]=useState(()=>stored('lifevault-items',seed)),[profile,setProfile]=useState(()=>stored('lifevault-profile',{name:'Your Name',headline:'Creator · Learner · Explorer',location:'Your corner of the world',bio:'A life is made of a thousand little chapters. Here are mine.'})),[query,setQuery]=useState(''),[open,setOpen]=useState(''),[mobile,setMobile]=useState(false),[current,setCurrent]=useState(null),[draft,setDraft]=useState({type:'Project',title:'',description:'',year:String(new Date().getFullYear()),visibility:'Public'}),[edit,setEdit]=useState(profile);
useEffect(()=>localStorage.setItem('lifevault-items',JSON.stringify(items)),[items]);
useEffect(()=>localStorage.setItem('lifevault-profile',JSON.stringify(profile)),[profile]);
const filtered=items.filter(i=>(!lookup[page]||i.type===lookup[page])&&[i.title,i.description,i.type,i.year].join(' ').toLowerCase().includes(query.toLowerCase()));
const nav=p=>{setPage(p);setMobile(false);setQuery('')};
const beginAdd=()=>{setDraft({type:'Project',title:'',description:'',year:String(new Date().getFullYear()),visibility:'Public'});setOpen('add')};
const save=()=>{if(!draft.title.trim())return;setItems(v=>[{...draft,title:draft.title.trim(),id:Date.now()},...v]);setOpen('')};
const deleteItem=()=>{setItems(v=>v.filter(i=>i.id!==current.id));setOpen('')};
const tile=(i,n)=> <button key={i.id} className="story-card" onClick={()=>{setCurrent(i);setOpen('detail')}}><div className={'tile-cover tile-'+(n%4)}><span>{emoji[i.type]}</span><span className="cover-circle"/></div><div className="tile-body"><small>{i.type} · {i.year}</small><h3>{i.title}</h3><p>{i.description}</p><div className="tile-bottom"><span>{i.visibility}</span><ArrowUpRight size={19}/></div></div></button>;
return <div className="app"><aside className={'sidebar '+(mobile?'mobile-show':'')}><button className="brand" onClick={()=>nav('Home')}><span className="brand-mark"><Layers3 size={22}/></span><strong>LifeVault</strong></button><span className="nav-caption">YOUR SPACE</span><nav>{menu.map(([name,Icon])=><button key={name} onClick={()=>nav(name)} className={'nav-entry '+(page===name?'selected':'')}><Icon size={19}/>{name}</button>)}</nav><div className="sidebar-bottom"><div className="encourage"><span>✦ A LITTLE MORE, EVERY DAY</span><h3>Every chapter counts.</h3><p>Big milestones, little moments—save the things that make you, you.</p><button onClick={beginAdd}>Add a milestone <ArrowRight size={15}/></button></div><button className="nav-entry" onClick={()=>setOpen('about')}><Settings size={19}/> About this demo</button></div></aside>
{mobile&&<button className="mobile-mask" aria-label="Close menu" onClick={()=>setMobile(false)}/>}
<div className="workspace"><header className="topbar"><button className="menu-mobile" onClick={()=>setMobile(true)} aria-label="Open menu"><Menu/></button><label className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your story..."/></label><span className="demo-tag">FRONTEND PREVIEW</span><button className="top-add" onClick={beginAdd}><Plus size={18}/> Add new</button><button className="round-avatar" aria-label="Edit profile" onClick={()=>{setEdit(profile);setOpen('profile')}}>{profile.name[0].toUpperCase()}</button></header>
<main><div className="page-heading"><div><span className="eyebrow"><Sparkles size={15}/> YOUR SPACE, YOUR STORY</span><h1>{page==='Home'?'A life worth remembering.':page}</h1><p>{page==='Home'?'Collect what matters, celebrate your progress, and make it yours.':'Make every chapter a part of your story.'}</p></div><button className="outline-button" onClick={()=>setOpen('preview')}><Eye size={17}/> Preview profile <ArrowUpRight size={15}/></button></div>
{page==='Home'?<><section className="hero"><div className="landscape"><div className="sun"/><div className="mountains back"/><div className="mountains middle"/><div className="mountains front"/></div><div className="hero-words"><span>WELCOME TO YOUR STORY</span><h2>Everything that makes you, <em>you.</em></h2><p>One beautiful home for your milestones, projects, and proud moments.</p><button onClick={beginAdd}>Start a new chapter <ArrowRight size={18}/></button></div></section>
<section className="profile-card"><div className="big-avatar">{profile.name[0].toUpperCase()}</div><div className="identity"><h2>{profile.name}</h2><p>{profile.headline}</p><small>{profile.location}</small><button onClick={()=>{setEdit(profile);setOpen('profile')}}>Edit profile <ArrowUpRight size={14}/></button></div><div className="stat"><strong>{items.length}</strong><small>Moments saved</small></div><div className="stat"><strong>{items.filter(x=>x.type==='Project').length}</strong><small>Projects</small></div><div className="stat"><strong>{items.filter(x=>x.type==='Achievement').length}</strong><small>Achievements</small></div></section>
<div className="section-head"><div><small>COLLECT YOUR FAVORITES</small><h2>Your highlights <span>✦</span></h2></div><button className="text-action" onClick={()=>nav('My Journey')}>View everything <ArrowRight size={17}/></button></div><section className="tiles">{filtered.slice(0,3).map(tile)}</section>
<div className="bottom-grid"><section className="panel"><div className="section-head compact"><div><small>THE BIG PICTURE</small><h2>My journey</h2></div><button className="text-action" onClick={()=>nav('My Journey')}>Explore <ArrowRight size={16}/></button></div><div className="timeline">{[...items].sort((a,b)=>Number(a.year)-Number(b.year)).slice(0,5).map(i=><button key={i.id} onClick={()=>{setCurrent(i);setOpen('detail')}}><span className="timeline-emoji">{emoji[i.type]}</span><strong>{i.year}</strong><small>{i.title}</small></button>)}</div></section><section className="panel next"><span className="sparkle">✦</span><small>MAKE IT YOURS</small><h2>What's your next chapter?</h2><p>A project, a milestone, a small win—it all belongs here.</p><button onClick={beginAdd}>Add something new <ArrowRight size={16}/></button></section></div></>:
<><div className="section-head"><div><small>YOUR COLLECTION</small><h2>{page==='My Journey'?'All your chapters':page}</h2><p>{filtered.length} {filtered.length===1?'entry':'entries'} saved</p></div><button className="top-add" onClick={beginAdd}><Plus size={18}/> Add entry</button></div><section className="tiles collection">{filtered.map(tile)}</section>{filtered.length===0&&<div className="empty"><span>✦</span><h3>Your next chapter starts here.</h3><p>There aren't any entries in this space yet.</p><button className="top-add" onClick={beginAdd}>Add your first entry <Plus size={16}/></button></div>}</>}
<footer>Made for the moments that matter. <span>LifeVault · Frontend preview</span></footer></main></div>
{open&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen('')}}><section className="modal"><button className="close" aria-label="Close" onClick={()=>setOpen('')}><X size={20}/></button>
{open==='add'?<><small className="eyebrow">YOUR NEXT CHAPTER</small><h2>Add to your LifeVault</h2><p>Every milestone counts, big or small.</p><label>Category</label><select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}>{Object.keys(emoji).map(t=><option key={t}>{t}</option>)}</select><label>Title</label><input placeholder="What would you like to remember?" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><label>Description</label><textarea placeholder="What's the story?" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/><div className="form-columns"><div><label>Year</label><input value={draft.year} onChange={e=>setDraft({...draft,year:e.target.value})}/></div><div><label>Visibility</label><select value={draft.visibility} onChange={e=>setDraft({...draft,visibility:e.target.value})}><option>Public</option><option>Private</option></select></div></div><p className="note"><Lock size={15}/> Visibility is only simulated; entries remain in this browser.</p><button className="submit" onClick={save}>Save chapter <Check size={18}/></button></>:
open==='profile'?<><small className="eyebrow">MAKE IT PERSONAL</small><h2>Edit your profile</h2><p>Introduce yourself in your own words.</p>{[['name','Name'],['headline','Headline'],['location','Location'],['bio','Your story']].map(([k,label])=><React.Fragment key={k}><label>{label}</label><input value={edit[k]} onChange={e=>setEdit({...edit,[k]:e.target.value})}/></React.Fragment>)}<button className="submit" onClick={()=>{setProfile(edit);setOpen('')}}>Save profile <Check size={18}/></button></>:
open==='detail'?<><small className="eyebrow">{current.type} · {current.year}</small><div className="detail-symbol">{emoji[current.type]}</div><h2>{current.title}</h2><p>{current.description}</p><div className="detail-footer"><span>{current.visibility==='Private'?<Lock size={15}/>:<Globe size={15}/>} {current.visibility}</span><button onClick={deleteItem}><Trash2 size={16}/> Delete entry</button></div></>:
open==='preview'?<><small className="eyebrow">PUBLIC PROFILE PREVIEW</small><h2>{profile.name}</h2><p>{profile.headline}</p><p>{profile.bio}</p><div className="preview-list">{items.filter(i=>i.visibility==='Public').map(i=><div key={i.id}><span>{emoji[i.type]} {i.title}</span><small>{i.year}</small></div>)}</div><p className="note"><Globe size={15}/> This is a local preview, not a published profile URL.</p></>:
<><small className="eyebrow">LIFEVAULT V1</small><h2>A working frontend prototype</h2><p>Your entries and profile are saved in your browser only. Real authentication, document uploading, private cloud storage and public profile URLs are not implemented yet.</p></>}
</section></div>}
</div>}
createRoot(document.getElementById('root')).render(<App/>);
