import React,{useState,useEffect,useRef} from 'react';
import{createRoot}from'react-dom/client';
import{Layers2,House,Clock3,Archive,BriefcaseBusiness,FolderKanban,Trophy,GraduationCap,LockKeyhole,Plus,Search,ArrowUpRight,ArrowRight,ArrowLeft,ChevronRight,Menu,X,Pencil,Trash2,Check,Eye,Sun,Moon,FileText,BookOpen,Feather,MapPin,CalendarDays,Heart,ShieldAlert,Command,Download,Upload,RotateCcw}from'lucide-react';
import{emptyForm,collectionFor,safeId,allEntries}from'./data.js';
import './redesign.css';
import Collections from './collections.jsx';
import Professional from './professional.jsx';
import AiSuggest from './ai.jsx';
import AuthPage from './AuthPage.jsx';
import AuthBadge from './AuthBadge.jsx';
import CloudWorkspace,{useCloudDoc,useAccount} from './cloud.jsx';
import {SharedPage} from './share.jsx';
const NAV=[['/','My Space',House],['/collections','My Stories',BookOpen],['/archive','Explore',Archive],['/professional','Professional',BriefcaseBusiness],['/vault','The Vault',LockKeyhole]];
const SUBNAV=[['/timeline','My Journey'],['/memories','Memories'],['/experience','Experiences'],['/projects','Creations'],['/achievements','Milestones'],['/education','Learning']];
const labels={Experience:'experiences',Project:'projects',Achievement:'achievements',Education:'education',Memory:'memories'};
const paths={Experience:'/experience',Project:'/projects',Achievement:'/achievements',Education:'/education',Memory:'/memories'};
const Icons={Experience:BriefcaseBusiness,Project:FolderKanban,Achievement:Trophy,Education:GraduationCap,Memory:BookOpen};
const types=['Memory','Experience','Project','Achievement','Education'];
const categoryNames={Memory:'Memory',Experience:'Life experience',Project:'Creation',Achievement:'Milestone',Education:'Learning'};
const experienceKind=x=>x.kind||(x.role?'Work':'Life');
const norm=p=>p.replace(/\/+$/,'')||'/';
const title=x=>x.organization||x.title||'Untitled';
const stamp=x=>String(x.date||x.year||x.timeframe||'').match(/(?:19|20)\d{2}/)?.[0]||'';
const dateOf=x=>{const yr=stamp(x);return yr?Number(yr):0};
const hasOwn=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
function App(){
 const account=useAccount();
 const [portrait,setPortrait]=useState(account.user.avatar||'');
 useEffect(()=>{const handler=e=>setPortrait(e.detail.avatar||'');window.addEventListener('lifevault:avatar',handler);return()=>window.removeEventListener('lifevault:avatar',handler)},[]);
 const [data,setData,syncStatus]=useCloudDoc('space');
 const [path,setPath]=useState(norm(location.pathname)),[mobile,setMobile]=useState(false),[dialog,setDialog]=useState(''),[form,setForm]=useState(emptyForm('Memory')),[editing,setEditing]=useState(null),[draftProfile,setDraftProfile]=useState(data.profile);
 const [q,setQ]=useState(''),[filter,setFilter]=useState('All'),[preview,setPreview]=useState(false),[dark,setDark]=useState(()=>localStorage.getItem('lifevault-theme')==='dark'),[notice,setNotice]=useState('');
 const searchRef=useRef(null),fileRef=useRef(null),toastRef=useRef(null);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('lifevault-theme',dark?'dark':'light')},[dark]);
 useEffect(()=>{const f=()=>{setPath(norm(location.pathname));setQ('')};window.addEventListener('popstate',f);return()=>window.removeEventListener('popstate',f)},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3700);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{const k=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setDialog('search')}if(e.key==='Escape')setDialog('')};window.addEventListener('keydown',k);return()=>window.removeEventListener('keydown',k)},[]);
 useEffect(()=>{if(dialog==='search')searchRef.current?.focus()},[dialog]);
 const go=(p)=>{history.pushState({},'',p);setPath(p);setMobile(false);setDialog('');setQ('');window.scrollTo({top:0,behavior:'instant'})};
 const openAdd=(type='Memory',organizationId='')=>{setForm({...emptyForm(type),organizationId});setEditing(null);setDialog('capture')};
 const openEdit=(type,item)=>{setForm({...emptyForm(type),...item,type});setEditing(item.id);setDialog('capture')};
 const save=(e)=>{e.preventDefault();const target=form.type==='Experience'?'organization':'title';if(!String(form[target]||'').trim()){setNotice('Please add a title to continue.');return}const key=labels[form.type];const item={...form,id:editing||safeId(),[target]:form[target].trim(),updatedAt:new Date().toISOString()};delete item.type;if(form.type!=='Project')delete item.organizationId;setData(d=>({...d,[key]:editing?d[key].map(x=>x.id===editing?item:x):[item,...d[key]]}));setDialog('');setNotice(editing?'Chapter updated.':'Saved to your LifeVault.')};
 const remove=(type,item)=>{if(!window.confirm('Delete this entry? This cannot be undone.'))return;const key=labels[type];setData(d=>({...d,[key]:d[key].filter(x=>x.id!==item.id),...(type==='Experience'?{projects:d.projects.map(p=>p.organizationId===item.id?{...p,organizationId:''}:p)}:{})}));const own=paths[type];if(path.startsWith(own+'/'))go(own);setNotice('Entry removed.')};
 const org=id=>data.experiences.find(x=>x.id===id);
 const visible=items=>items.filter(x=>!preview||x.visibility!=='Private');
 const matches=x=>[title(x),x.role,x.description,x.issuer,x.year,x.timeframe,x.kind].join(' ').toLowerCase().includes(q.toLowerCase());
 const entries=visible(allEntries(data)).sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||'')||dateOf(b)-dateOf(a));
 const searchItems=entries.filter(matches).filter(x=>filter==='All'||x.type===filter);
 const displayYear=x=>x.date||x.year||x.timeframe||'Undated';
 const detailUrl=x=>(paths[x.type]||'/archive')+(x.id?'/'+encodeURIComponent(x.id):'');
 const accentIcon=x=>{const Icon=x.type==='Experience'?MapPin:(Icons[x.type]||BookOpen);return <Icon size={17} strokeWidth={1.65}/>};
 const control=(type,item)=>!preview&&<div className="entry-controls"><button onClick={e=>{e.stopPropagation();openEdit(type,item)}} aria-label={'Edit '+title(item)}><Pencil size={15}/> Edit</button><button className="danger" onClick={e=>{e.stopPropagation();remove(type,item)}} aria-label={'Delete '+title(item)}><Trash2 size={15}/> Delete</button></div>;
 const linked=x=>x.type==='Project'&&x.organizationId&&org(x.organizationId);
 const eyebrow=children=><div className="eyebrow"><span className="eyebrow-mark"/> {children}</div>;
 const heading=(small,big,desc,type)=> <div className="page-head"><div>{eyebrow(small)}<h1>{big}</h1><p>{desc}</p></div>{type&&!preview&&<button className="quiet-button" onClick={()=>openAdd(type)}><Plus size={17}/> Add {type.toLowerCase()}</button>}</div>;
 const row=(x,href=detailUrl(x))=><article className="archive-row" key={x.type+':'+x.id}>
  <button className="archive-row-main" onClick={()=>go(href)}><span className="archive-icon">{accentIcon(x)}</span><span className="archive-row-copy"><span className="archive-type">{categoryNames[x.type]||x.type}{x.type==='Experience'?' · '+experienceKind(x):''}{linked(x)?' · '+org(x.organizationId).organization:''}{x.kind&&x.type==='Memory'?' · '+x.kind:''}</span><strong>{title(x)}</strong><span className="archive-description">{x.description||x.role||x.issuer||'Open this chapter'}</span></span><span className="archive-date">{displayYear(x)}</span><ArrowUpRight size={19} className="row-arrow"/></button>
  {control(x.type,x)}
 </article>;
 const empty=(kind='chapter',type='Memory')=><div className="empty"><span className="empty-glyph">✳</span><h3>A page waiting to be written.</h3><p>{kind==='search'?'Nothing matches yet. Try a different word or category.':'Your '+kind+' will find its place here, whenever you are ready.'}</p>{kind!=='search'&&!preview&&<button className="primary" onClick={()=>openAdd(type)}><Plus size={16}/> Add a chapter</button>}</div>;
 const dataList=(type,subset)=>visible(subset??data[labels[type]]).filter(matches).map(x=>row({...x,type}));
 const recordDetail=(type,item,back)=> <><button className="back" onClick={()=>go(back)}><ArrowLeft size={17}/> Back to {back==='/experience'?'experience':back==='/projects'?'projects':back==='/memories'?'moments':back==='/education'?'education':back==='/achievements'?'achievements':'archive'}</button>
 <section className="record-sheet"><div className="sheet-top">{eyebrow(type==='Memory'?(item.kind||'Moment'):type)}<span>{displayYear(item)}</span></div><div className="sheet-rule"/><h1>{title(item)}</h1>{item.role&&<p className="sheet-subtitle">{item.role}</p>}{item.issuer&&<p className="sheet-subtitle">{item.issuer}</p>}{item.location&&<p className="sheet-subtitle"><MapPin size={15}/> {item.location}</p>}{item.description?<p className="sheet-description">{item.description}</p>:<p className="sheet-description muted">There's room for more of this story whenever you're ready.</p>}<div className="sheet-bottom"><span>{item.visibility==='Private'?'Marked private':'Marked public'} · Browser storage only</span>{control(type,item)}</div></section>
 {type==='Experience'&&<section className="subsection"><div className="subsection-head"><div>{eyebrow('CONNECTED CREATIONS')}<h2>Things connected to this experience</h2><p>Any creations linked to this experience will appear here.</p></div>{!preview&&<button className="quiet-button" onClick={()=>openAdd('Project',item.id)}><Plus size={16}/> Add project</button>}</div>{visible(data.projects.filter(p=>p.organizationId===item.id)).length?visible(data.projects.filter(p=>p.organizationId===item.id)).map(p=>row({...p,type:'Project'})):empty('connected projects','Project')}</section>}
 {type==='Project'&&org(item.organizationId)&&<button className="related" onClick={()=>go('/experience/'+encodeURIComponent(item.organizationId))}><BriefcaseBusiness size={19}/><span><small>PART OF THIS EXPERIENCE</small><strong>{org(item.organizationId).organization}</strong></span><ArrowRight size={17}/></button>}</>;
 const findDetail=(base,coll)=>path.startsWith(base+'/')?visible(coll).find(x=>x.id===decodeURIComponent(path.slice(base.length+1))):null;
 const exp=findDetail('/experience',data.experiences),proj=findDetail('/projects',data.projects),memory=findDetail('/memories',data.memories),ach=findDetail('/achievements',data.achievements),edu=findDetail('/education',data.education);
 const sectionCards=[
 {name:'Collections',number:'01',hint:'Trip pages, photo stories and shareable moments',link:'/collections',icon:BookOpen},
 {name:'Memories',number:'02',hint:'Moments you want to remember',link:'/memories',icon:Heart},
 {name:'Experiences',number:'03',hint:'Places, travels and adventures',link:'/experience',icon:MapPin},
 {name:'Creations',number:'04',hint:'Anything you have made',link:'/projects',icon:FolderKanban},
 {name:'Milestones',number:'05',hint:'Little and big wins',link:'/achievements',icon:Trophy},
 {name:'Learning',number:'06',hint:'Lessons, skills and education',link:'/education',icon:GraduationCap},
 {name:'The Vault',number:'07',hint:'Your future private collection',link:'/vault',icon:LockKeyhole}
 ];
 const recent=entries.filter(x=>x.updatedAt).slice(0,3);
 const exportData=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='lifevault-backup.json';a.click();URL.revokeObjectURL(url);setNotice('Backup downloaded.')};
 const importData=e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const obj=JSON.parse(String(reader.result));if(!Array.isArray(obj.experiences)||!Array.isArray(obj.projects)||!Array.isArray(obj.achievements)||!Array.isArray(obj.education)||!obj.profile||typeof obj.profile!=='object')throw Error();if(!window.confirm('Restore this backup? It replaces your current browser entries.'))return;setData({...obj,memories:Array.isArray(obj.memories)?obj.memories:[]});setNotice('Backup restored.')}catch{setNotice('That file is not a valid LifeVault backup.')}};reader.readAsText(file);e.target.value=''};
 return <div className="shell">
 <aside className={'rail '+(mobile?'rail-open':'')}><button className="brand" onClick={()=>go('/')}><span className="brand-icon"><Layers2 size={21}/></span><span>lifevault<small>YOUR STORY, IN ONE PLACE</small></span></button><span className="rail-caption">YOUR SPACE</span><nav aria-label="Main navigation">{NAV.map(([p,label,Icon],i)=><button key={p} onClick={()=>go(p)} className={(p==='/'?path==='/':path===p||path.startsWith(p+'/'))?'active':''}><Icon size={18} strokeWidth={1.65}/><span>{label}</span>{i===2&&entries.length>0&&<span className="rail-index">{entries.length}</span>}</button>)}</nav><div className="rail-bottom"><AuthBadge/><div className="rail-quote">“The details make a life.”<span>— A place for what matters</span></div><button onClick={()=>setDark(x=>!x)}><span>{dark?<Sun size={18}/>:<Moon size={18}/>}</span> {dark?'Restore daylight':'Dim the lights'}</button></div></aside>
 {mobile&&<button className="veil" aria-label="Close menu" onClick={()=>setMobile(false)}/>}
 <div className="main"><header className="topbar"><button className="menu-trigger" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={22}/></button><div className="breadcrumb"><span>LifeVault</span><ChevronRight size={14}/><strong>{NAV.find(([p])=>p==='/'?path==='/':path===p||path.startsWith(p+'/'))?.[1]||SUBNAV.find(([p])=>path===p||path.startsWith(p+'/'))?.[1]||'Chapter'}</strong></div><div className="top-actions"><button className="search-trigger" onClick={()=>setDialog('search')}><Search size={18}/><span>Search anything</span><kbd>⌘ K</kbd></button>{!preview&&<button className="primary top-capture" onClick={()=>openAdd()}><Plus size={17}/> Add a chapter</button>}<button className="top-avatar" onClick={()=>{setDraftProfile({...data.profile});setDialog('profile')}} title="Edit your personal introduction">{portrait?<img src={portrait} alt="Your profile picture" className="lv-top-portrait"/>:(account.user.name||'Y').charAt(0).toUpperCase()}</button></div></header>
 <main className="content">{syncStatus&&<div className="cloud-save-status" role="status">{syncStatus}</div>}
 {preview&&<div className="privacy-note"><Eye size={16}/> Display preview hides entries marked private. It is not a published profile or secure access boundary.</div>}
 {path==='/'&&<><section className="second-home">
<div className="second-welcome"><div><span className="second-eyebrow">YOUR PERSONAL SPACE</span><div className="lv-personal-intro">{portrait?<img src={portrait} alt="Your profile picture"/>:<span className="lv-personal-placeholder">{(account.user.name||'Y').charAt(0).toUpperCase()}</span>}<div><h1>Welcome, {account.user.name.split(' ')[0]}<span className="second-comma">.</span></h1><p>This is your space for the people, places and chapters that make life yours.</p><button className="lv-intro-edit" onClick={()=>{setDraftProfile({...data.profile});setDialog('profile')}}>Edit your introduction <ArrowUpRight size={14}/></button></div></div></div><div className="second-quote">“A life well remembered<br/>is a life well lived.”</div></div>
<div className="second-quick"><button onClick={()=>openAdd('Memory')}><span className="quick-icon memory"><Heart size={22}/></span><strong>Add a memory</strong></button><button onClick={()=>go('/collections')}><span className="quick-icon trip"><MapPin size={22}/></span><strong>Make a trip page</strong></button><button onClick={()=>openAdd('Memory')}><span className="quick-icon note"><FileText size={22}/></span><strong>Write a note</strong></button><button onClick={()=>openAdd('Achievement')}><span className="quick-icon milestone"><Trophy size={22}/></span><strong>Mark a milestone</strong></button><button onClick={()=>go('/archive')}><span className="quick-icon more"><Plus size={22}/></span><strong>Explore more</strong></button></div>
<div className="second-section-head"><div><span className="second-eyebrow">YOUR STORY, YOUR WAY</span><h2>Stories to look back on</h2></div><button className="text-link" onClick={()=>go('/collections')}>View all <ArrowRight size={17}/></button></div>
<div className="second-collection-teaser"><button className="second-new-collection" onClick={()=>go('/collections')}><span><Plus size={25}/></span><strong>Start a collection</strong><small>A trip, a celebration, a favorite place—anything worth keeping.</small><span className="second-new-arrow">Make a page <ArrowUpRight size={16}/></span></button><button className="second-teaser-card" onClick={()=>go('/collections')}><div className="second-card-art art-trip"><MapPin size={35}/></div><strong>Travel & places</strong><small>Keep your adventures together</small></button><button className="second-teaser-card" onClick={()=>go('/collections')}><div className="second-card-art art-memories"><Heart size={35}/></div><strong>People & moments</strong><small>Stories that feel like home</small></button></div>
<div className="second-lower"><section><div className="second-section-head"><div><span className="second-eyebrow">PICK UP WHERE YOU LEFT OFF</span><h2>Recently saved</h2></div><button className="text-link" onClick={()=>go('/archive')}>See all <ArrowRight size={16}/></button></div>{recent.length?recent.map(x=>row(x)):<div className="second-empty">Your first saved moment will appear here. <button onClick={()=>openAdd('Memory')}>Add a memory <ArrowRight size={14}/></button></div>}</section><section className="second-side-note"><span className="second-eyebrow">ONE LIFE. MANY CHAPTERS.</span><h3>Make space for what matters.</h3><p>From a spontaneous weekend away to the things you're proud of—LifeVault is yours to shape.</p><button onClick={()=>go('/archive')}>Explore your space <ArrowUpRight size={17}/></button></section></div>
</section></>}
 {(path==='/collections'||path.startsWith('/collections/'))&&<Collections path={path} go={go} preview={preview}/>}
 {path==='/professional'&&<Professional preview={preview}/>}
 {path==='/timeline'&&<>{heading('YOUR LIFE UNFOLDING','The story so far.','A timeline of everything you have chosen to preserve.')}{entries.length?Object.entries(entries.reduce((acc,x)=>{const yr=stamp(x)||'Undated';(acc[yr]??=[]).push(x);return acc},{})).sort((a,b)=>(Number(b[0])||0)-(Number(a[0])||0)).map(([year,items])=><section className="timeline-year" key={year}><div className="year-label">{year}</div><div className="year-entries">{items.map(x=>row(x))}</div></section>):empty('timeline')}</>}
 {path==='/archive'&&<>{heading('CHOOSE WHAT TO OPEN','Explore your LifeVault.','A simple way to find places, memories, experiences, and everything you have saved.')}
 <div className="explore-gateway">
  <button onClick={()=>go('/timeline')}><Clock3 size={19}/><span><strong>My Journey</strong><small>See your story unfold over time</small></span><ArrowUpRight size={17}/></button>
  <button onClick={()=>go('/memories')}><BookOpen size={19}/><span><strong>Memories</strong><small>The moments you kept</small></span><ArrowUpRight size={17}/></button>
  <button onClick={()=>go('/experience')}><MapPin size={19}/><span><strong>Places & Experiences</strong><small>Travel, people, life, and adventures</small></span><ArrowUpRight size={17}/></button>
  <button onClick={()=>go('/projects')}><FolderKanban size={19}/><span><strong>Creations</strong><small>Things made, explored, and built</small></span><ArrowUpRight size={17}/></button>
  <button onClick={()=>go('/achievements')}><Trophy size={19}/><span><strong>Milestones</strong><small>Moments worth celebrating</small></span><ArrowUpRight size={17}/></button>
  <button onClick={()=>go('/education')}><GraduationCap size={19}/><span><strong>Learning</strong><small>Lessons, interests, and education</small></span><ArrowUpRight size={17}/></button>
 </div>
 <div className="explore-list-title"><div className="eyebrow"><span className="eyebrow-mark"/> ALL YOUR SAVED ENTRIES</div><h2>Find anything.</h2></div>
 <div className="archive-toolbar"><label className="inline-search"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search names, places, ideas..." aria-label="Search archive"/></label><div className="filter-row" role="group" aria-label="Filter by category">{['All',...types].map(t=><button className={filter===t?'chosen':''} onClick={()=>setFilter(t)} key={t}>{t==='All'?'All':({Memory:'Memories',Experience:'Experiences',Project:'Creations',Achievement:'Milestones',Education:'Learning'}[t])}</button>)}</div></div>}{searchItems.length?<div className="archive-list">{searchItems.map(x=>row(x))}</div>:empty('search')}</>}
 {path==='/experience'&&<>{heading('THE PLACES AND MOMENTS','Experiences',"Keep the places you have been, the people you have met, and the days worth remembering.",'Experience')}{visible(data.experiences).length?<div className="archive-list">{visible(data.experiences).map(x=>row({...x,type:'Experience'}))}</div>:empty('experience','Experience')}</>}
 {exp&&recordDetail('Experience',exp,'/experience')}
 {path==='/projects'&&<>{heading('ALL THE THINGS YOU CREATE','Creations',"Art, hobbies, personal projects, and things you have made.",'Project')}{data.experiences.map(e=>{const ps=visible(data.projects.filter(x=>x.organizationId===e.id));return ps.length?<section className="project-group" key={e.id}><div className="subsection-head"><div>{eyebrow('CONNECTED TO AN EXPERIENCE')}<h2>{e.organization}</h2></div><button className="text-link" onClick={()=>go('/experience/'+encodeURIComponent(e.id))}>Visit chapter <ArrowUpRight size={17}/></button></div>{ps.map(x=>row({...x,type:'Project'}))}</section>:null})}{(()=>{const ps=visible(data.projects.filter(x=>!x.organizationId||!org(x.organizationId)));return ps.length?<section className="project-group"><div className="subsection-head"><div>{eyebrow('PERSONAL CREATIONS')}<h2>Things I've made</h2></div></div>{ps.map(x=>row({...x,type:'Project'}))}</section>:null})()}{visible(data.projects).length===0&&empty('projects','Project')}</>}
 {proj&&<>{recordDetail('Project',proj,org(proj.organizationId)?'/experience/'+encodeURIComponent(proj.organizationId):'/projects')}{org(proj.organizationId)&&<button className="related" onClick={()=>go('/experience/'+encodeURIComponent(proj.organizationId))}><BriefcaseBusiness size={20}/><span><small>PART OF THIS EXPERIENCE</small><strong>{org(proj.organizationId).organization}</strong></span><ArrowRight size={17}/></button>}</>}
 {path==='/achievements'&&<>{heading('MOMENTS WORTH CELEBRATING','Milestones','Your wins, personal firsts and meaningful achievements.','Achievement')}{visible(data.achievements).length?<div className="archive-list">{dataList('Achievement')}</div>:empty('achievements','Achievement')}</>}
 {ach&&recordDetail('Achievement',ach,'/achievements')}
 {path==='/education'&&<>{heading('ALWAYS LEARNING','Learning','Classes, personal discoveries and skills you have picked up.','Education')}{visible(data.education).length?<div className="archive-list">{dataList('Education')}</div>:empty('education','Education')}</>}
 {edu&&recordDetail('Education',edu,'/education')}
 {path==='/memories'&&<>{heading('THE LITTLE THINGS','Memories','Photos someday, notes today—and stories you never want to forget.','Memory')}{visible(data.memories).length?<div className="archive-list">{dataList('Memory')}</div>:empty('moments','Memory')}</>}
 {memory&&recordDetail('Memory',memory,'/memories')}
 {path==='/vault'&&<>{heading('THE PRIVATE COLLECTION','My Vault','A home for the things you keep close.') }<div className="vault"><span className="vault-symbol"><LockKeyhole size={27}/></span>{eyebrow('A ROOM NOT YET OPEN')}<h2>Some things deserve a quieter place.</h2><p>Secure document upload and account-based privacy are not available yet. To protect your information, this prototype deliberately does not accept sensitive files or claim that its data is encrypted.</p><div className="vault-status"><ShieldAlert size={17}/> Currently saved only in this browser</div></div><section className="backup"><div><h3>Take your collection with you.</h3><p>Download a JSON backup of the entries stored in this browser, or restore a previous LifeVault backup.</p></div><div className="backup-buttons"><button className="quiet-button" onClick={exportData}><Download size={16}/> Export backup</button><button className="quiet-button" onClick={()=>fileRef.current?.click()}><Upload size={16}/> Restore backup</button><input ref={fileRef} type="file" accept="application/json,.json" hidden onChange={importData}/></div></section></>}
 {!NAV.some(([p])=>p==='/'?path==='/':path===p||path.startsWith(p+'/'))&&!exp&&!proj&&!memory&&!ach&&!edu&&<div className="empty"><h2>This chapter could not be found.</h2><button className="primary" onClick={()=>go('/')}>Return home <ArrowRight size={16}/></button></div>}
 <footer className="footer"><span>lifevault — a home for all of you.</span><span>Preview · Your data lives in this browser</span></footer></main>
 </div>
 {dialog&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDialog('')}}><div className={'modal '+(dialog==='search'?'modal-search':'')} role="dialog" aria-modal="true" aria-label={dialog==='capture'?'Add a chapter':dialog==='profile'?'Edit introduction':'Search LifeVault'}><button className="modal-close" aria-label="Close" onClick={()=>setDialog('')}><X size={21}/></button>
 {dialog==='capture'&&<form onSubmit={save}>{eyebrow(editing?'REFINE A CHAPTER':'MAKE ROOM FOR A MOMENT')}<h2>{editing?'Edit this chapter.':'What would you like to keep?'}</h2><p>Capture the essentials now. The rest can come later.</p><label>What would you like to save?</label><select disabled={!!editing} value={form.type} onChange={e=>setForm(emptyForm(e.target.value))}>{types.map(t=><option key={t} value={t}>{({Memory:'A memory or note',Experience:'A place or life experience',Project:'Something I made',Achievement:'A milestone or win',Education:'Something I learned'})[t]}</option>)}</select>
 {form.type==='Experience'?<><label>Give this experience a name <b>*</b></label><input required value={form.organization} onChange={e=>setForm({...form,organization:e.target.value})} placeholder="e.g. A trip to Georgia, My first concert, Summer in Nepal"/><label>Type of experience</label><select value={experienceKind(form)} onChange={e=>setForm({...form,kind:e.target.value})}>{['Travel','Life','Work','Family','Adventure','Other'].map(t=><option key={t}>{t}</option>)}</select>{experienceKind(form)==='Work'&&<><label>Role (optional)</label><input value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/></>}<label>When?</label><input value={form.timeframe} onChange={e=>setForm({...form,timeframe:e.target.value})} placeholder="e.g. 2024–2026"/><label>Place (optional)</label><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></>:<><label>Title <b>*</b></label><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder={form.type==='Memory'?'Give this moment a name':'What would you call this chapter?'}/>{form.type==='Memory'?<><label>Kind of moment</label><select value={form.kind||'Moment'} onChange={e=>setForm({...form,kind:e.target.value})}><option>Moment</option><option>Note</option><option>Milestone</option></select><label>Date</label><input type="date" value={form.date||''} onChange={e=>setForm({...form,date:e.target.value})}/></>:<><label>Year</label><input value={form.year||''} onChange={e=>setForm({...form,year:e.target.value})} placeholder="e.g. 2026"/>{form.type==='Project'?<><label>Related experience</label><select value={form.organizationId||''} onChange={e=>setForm({...form,organizationId:e.target.value})}><option value="">Independent project</option>{data.experiences.map(x=><option value={x.id} key={x.id}>{x.organization}</option>)}</select></>:<><label>{form.type==='Education'?'School or institution':'Awarded by (optional)'}</label><input value={form.issuer||''} onChange={e=>setForm({...form,issuer:e.target.value})}/></>}</>}</>}
 <label>{form.type==='Memory'?'The story':'A few words about it'}</label><textarea rows={4} value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Write as much or as little as you wish..."/>
 <AiSuggest purpose="story" text={[form.title,form.organization,form.description].filter(Boolean).join('\n')} label="Polish this memory" onApply={value=>setForm(x=>({...x,description:value}))}/>
 <AiSuggest purpose="tags" text={[form.title,form.organization,form.description].filter(Boolean).join('\n')} label="Suggest search tags" onApply={value=>setForm(x=>({...x,description:[x.description,'Tags: '+value].filter(Boolean).join('\n\n')}))}/>
 <label>Visibility label</label><select value={form.visibility||'Public'} onChange={e=>setForm({...form,visibility:e.target.value})}><option>Public</option><option>Private</option></select><p className="form-disclaimer"><ShieldAlert size={16}/> This is browser storage, not secure or account-protected. Please do not save sensitive data.</p><button className="primary modal-submit" type="submit"><Check size={17}/> Save this chapter</button></form>}
 {dialog==='profile'&&<form onSubmit={e=>{e.preventDefault();setData(d=>({...d,profile:draftProfile}));setDialog('');setNotice('Introduction updated.')}}>{eyebrow('PERSONAL INTRODUCTION')}<h2>In your own words.</h2><p>Keep it real, simple, and yours.</p>{[['name','Name'],['subtitle','One-line introduction'],['about','A little about you'],['location','Location (optional)']].map(([k,label])=><React.Fragment key={k}><label>{label}</label>{k==='about'?<textarea rows={3} value={draftProfile[k]||''} onChange={e=>setDraftProfile({...draftProfile,[k]:e.target.value})}/>:<input value={draftProfile[k]||''} onChange={e=>setDraftProfile({...draftProfile,[k]:e.target.value})}/>}</React.Fragment>)}<button className="primary modal-submit" type="submit"><Check size={17}/> Save introduction</button></form>}
 {dialog==='search'&&<><div className="search-dialog-head"><Search size={21}/><input ref={searchRef} aria-label="Search your collection" placeholder="Find a person, project, memory..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="search-dialog-results">{entries.filter(matches).slice(0,8).map(x=><button key={x.type+x.id} onClick={()=>go(detailUrl(x))}><span>{accentIcon(x)}</span><span><strong>{title(x)}</strong><small>{x.type} · {displayYear(x)}</small></span><ArrowUpRight size={16}/></button>)}{!entries.filter(matches).length&&<p className="no-results">No matching chapters yet.</p>}</div><div className="search-dialog-foot">Search your locally saved collection · Esc to close</div></>}
 </div></div>}
 <div className="mobile-tabs">{[['/','My Space',House],['/collections','Collections',BookOpen],['/archive','Explore',Archive],['/professional','Professional',BriefcaseBusiness]].map(([u,label,Icon])=><button onClick={()=>go(u)} className={path===u?'active':''} key={u}><Icon size={20}/><span>{label}</span></button>)}<button className="mobile-add" onClick={()=>openAdd()} aria-label="Capture a new chapter"><Plus size={23}/><span>Add</span></button><button onClick={()=>setMobile(true)}><Menu size={20}/><span>More</span></button></div>
 {notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}
 </div>;
}
createRoot(document.getElementById('root')).render(location.pathname==='/share'?<SharedPage/>:<CloudWorkspace><App/></CloudWorkspace>);