import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Layers3,Home,BriefcaseBusiness,FolderKanban,Trophy,GraduationCap,LockKeyhole,Menu,X,Plus,ArrowRight,ArrowLeft,ArrowUpRight,Pencil,Trash2,Check,Globe2,Search,Sparkles,Settings,Eye,Heart,ChevronRight,ShieldCheck} from 'lucide-react';
import {initialData,saveData,emptyForm,collectionFor,safeId} from './data.js';
import './redesign.css';

const links=[['/','Home',Home],['/experience','Experience',BriefcaseBusiness],['/projects','Projects',FolderKanban],['/achievements','Achievements',Trophy],['/education','Education',GraduationCap],['/vault','My Vault',LockKeyhole]];
const sections=[['/experience','Experience','The places behind the work.',BriefcaseBusiness,'01'],['/projects','Projects','The things I have built and explored.',FolderKanban,'02'],['/achievements','Achievements','Recognition, milestones and meaningful wins.',Trophy,'03'],['/education','Education','The experiences that helped me learn.',GraduationCap,'04']];
const typeKeys={Experience:'experiences',Project:'projects',Achievement:'achievements',Education:'education'};
const normalPath=path=>path.replace(/\/+$/,'')||'/';
function App(){
 const [path,setPath]=useState(normalPath(location.pathname));
 const [data,setData]=useState(initialData);
 const [menu,setMenu]=useState(false),[modal,setModal]=useState(''),[preview,setPreview]=useState(false),[query,setQuery]=useState('');
 const [form,setForm]=useState(emptyForm()),[editing,setEditing]=useState(null),[profileDraft,setProfileDraft]=useState(data.profile);
 useEffect(()=>saveData(data),[data]);
 useEffect(()=>{const cb=()=>setPath(normalPath(location.pathname));window.addEventListener('popstate',cb);return()=>window.removeEventListener('popstate',cb)},[]);
 const go=to=>{history.pushState({},'',to);setPath(to);setMenu(false);setQuery('');window.scrollTo(0,0)};
 const add=(type='Project',org='')=>{setEditing(null);setForm({...emptyForm(type),organizationId:org});setModal('entry')};
 const edit=(type,item)=>{setEditing(item.id);setForm({...emptyForm(type),...item,type});setModal('entry')};
 const submit=e=>{e.preventDefault();const key=typeKeys[form.type];const target=form.type==='Experience'?'organization':'title';if(!String(form[target]||'').trim())return;const item={...form,id:editing||safeId(),[target]:form[target].trim()};delete item.type;if(form.type!=='Project')delete item.organizationId;setData(prev=>({...prev,[key]:editing?prev[key].map(x=>x.id===editing?item:x):[...prev[key],item]}));setModal('')};
 const remove=(type,item)=>{if(!confirm('Delete this entry? This cannot be undone.'))return;const key=typeKeys[type];setData(prev=>({...prev,[key]:prev[key].filter(x=>x.id!==item.id),...(type==='Experience'?{projects:prev.projects.map(x=>x.organizationId===item.id?{...x,organizationId:''}:x)}:{})}));if(path.endsWith('/'+encodeURIComponent(item.id)))go('/'+key)};
 const saveProfile=e=>{e.preventDefault();setData(prev=>({...prev,profile:profileDraft}));setModal('')};
 const orgById=id=>data.experiences.find(x=>x.id===id);
 const filtered=xs=>xs.filter(x=>(!preview||x.visibility!=='Private')&&[x.organization,x.title,x.role,x.description,x.issuer].join(' ').toLowerCase().includes(query.toLowerCase()));
 const actions=(type,item)=><div className="lv-actions">{!preview&&<><button onClick={()=>edit(type,item)}><Pencil size={15}/> Edit</button><button className="lv-delete" onClick={()=>remove(type,item)}><Trash2 size={15}/> Delete</button></>}</div>;
 const card=(type,item,url)=><article className="lv-entry" key={item.id}><div className="lv-entry-meta">{item.year||item.timeframe||type}<span className="lv-dot">·</span><span>{item.visibility==='Private'?'Private label':'Public label'}</span></div><h3>{item.organization||item.title}</h3>{item.role&&<div className="lv-role">{item.role}</div>}{item.issuer&&<div className="lv-role">{item.issuer}</div>}{item.location&&<div className="lv-role">{item.location}</div>}{item.description&&<p>{item.description}</p>}<div className="lv-entry-footer">{actions(type,item)}{url&&<button className="lv-textbutton" onClick={()=>go(url)}>Explore <ArrowRight size={17}/></button>}</div></article>;
 const head=(sub,title,desc,type)=><div className="lv-heading"><div><div className="lv-kicker"><Sparkles size={14}/>{sub}</div><h1>{title}</h1><p>{desc}</p></div>{!preview&&type&&<button className="lv-primary" onClick={()=>add(type)}><Plus size={16}/> Add {type.toLowerCase()}</button>}</div>;
 const none=(title,desc,type,Icon)=><div className="lv-empty"><span><Icon size={26}/></span><h3>{title}</h3><p>{desc}</p>{!preview&&<button className="lv-primary" onClick={()=>add(type)}><Plus size={16}/> Add an entry</button>}</div>;
 const search=<label className="lv-search"><Search size={18}/><input aria-label="Search this section" placeholder="Search this section..." value={query} onChange={e=>setQuery(e.target.value)}/></label>;
 const expId=path.startsWith('/experience/')?decodeURIComponent(path.slice(12)):null;
 const projectId=path.startsWith('/projects/')?decodeURIComponent(path.slice(10)):null;
 const exp=data.experiences.find(x=>x.id===expId);
 const project=data.projects.find(x=>x.id===projectId);
 const category=links.find(([url])=>url==='/'?path==='/':path===url||path.startsWith(url+'/'));
 return <div className="lv-app">
 <aside className={'lv-side '+(menu?'open':'')}><button className="lv-brand" onClick={()=>go('/')}><span><Layers3 size={24}/></span>LifeVault</button><div className="lv-side-caption">MY SPACE</div><nav>{links.map(([url,label,Icon])=><button key={url} className={(url==='/'?path==='/':path===url||path.startsWith(url+'/'))?'selected':''} onClick={()=>go(url)}><Icon size={19}/>{label}</button>)}</nav><div className="lv-side-bottom"><div className="lv-motto"><Heart size={22}/><strong>Every chapter counts.</strong><p>Make room for the moments that make you, you.</p></div><button className="lv-side-about" onClick={()=>setModal('about')}><Settings size={17}/> About LifeVault</button></div></aside>
 {menu&&<button className="lv-shade" onClick={()=>setMenu(false)} aria-label="Close navigation"/>}
 <div className="lv-main"><header className="lv-topbar"><button className="lv-menu" onClick={()=>setMenu(true)} aria-label="Open navigation"><Menu size={23}/></button><span className="lv-breadcrumb">My space <ChevronRight size={14}/> <strong>{category?category[1]:'Portfolio'}</strong></span><div className="lv-topright"><button className={'lv-preview '+(preview?'on':'')} onClick={()=>setPreview(x=>!x)}><Eye size={17}/>{preview?'Exit preview':'Preview'}</button>{!preview&&<button className="lv-primary" onClick={()=>add()}><Plus size={17}/> Add new</button>}<button className="lv-avatar" title="Edit profile" onClick={()=>{setProfileDraft({...data.profile});setModal('profile')}}>{(data.profile.name||'Y')[0]}</button></div></header>
 <main className="lv-content">{preview&&<div className="lv-preview-note"><Eye size={17}/> Preview hides editing controls and entries labeled private. This is not a published public profile.</div>}
 {path==='/'&&<><section className="lv-hero"><div className="lv-scene"><div className="lv-sun"/><div className="lv-hill one"/><div className="lv-hill two"/><div className="lv-hill three"/></div><div className="lv-hero-content"><div className="lv-kicker"><Sparkles size={14}/> A SPACE FOR YOUR STORY</div><h1>More than a profile.<br/><em>A whole journey.</em></h1><p>A thoughtful place for the things you've learned, built, and become. Explore at your own pace.</p><button className="lv-primary" onClick={()=>go('/experience')}>Explore my journey <ArrowRight size={17}/></button></div></section>
 <section className="lv-person"><div className="lv-person-avatar">{(data.profile.name||'Y')[0]}</div><div className="lv-person-copy"><span>HELLO, I'M</span><h2>{data.profile.name}</h2><p>{data.profile.subtitle||data.profile.headline}</p><p>{data.profile.about}</p></div>{!preview&&<button className="lv-outline" onClick={()=>{setProfileDraft({...data.profile});setModal('profile')}}>Edit introduction <Pencil size={15}/></button>}</section>
 <div className="lv-chapter-head"><div className="lv-kicker"><Sparkles size={14}/> EXPLORE THE CHAPTERS</div><h2>My story, organized.</h2><p>Not everything needs to live on the front page.</p></div>
 <div className="lv-chapters">{sections.map(([url,title,desc,Icon,num])=><button key={url} className="lv-chapter" onClick={()=>go(url)}><div className="lv-chapter-top"><span><Icon size={25}/></span><small>{num}</small></div><div className="lv-chapter-bottom"><div><h3>{title}</h3><p>{desc}</p></div><ArrowUpRight size={21}/></div></button>)}</div>
 <div className="lv-endnote"><span><Heart size={17}/> A place for every chapter.</span><button onClick={()=>go('/vault')}>Explore my vault <ArrowRight size={16}/></button></div></>}
 {path==='/experience'&&<>{head('PLACES AND PEOPLE','Experience','Open a place to see what I worked on there. Projects stay connected to their context.','Experience')}{search}<div className="lv-stack">{filtered(data.experiences).map(e=><div className="lv-work" key={e.id}><div className="lv-work-icon">{e.organization[0]}</div><div><small>{e.timeframe}</small><h2>{e.organization}</h2><p>{e.role}{e.location?' · '+e.location:''}</p><small>{data.projects.filter(p=>p.organizationId===e.id).length} associated project(s)</small></div><button className="lv-outline" onClick={()=>go('/experience/'+encodeURIComponent(e.id))}>Open chapter <ArrowRight size={17}/></button></div>)}</div>{!filtered(data.experiences).length&&none('Every experience has a story','Add an organization or place to begin.','Experience',BriefcaseBusiness)}</>}
 {expId&&exp&&<><button className="lv-back" onClick={()=>go('/experience')}><ArrowLeft size={17}/> All experience</button><div className="lv-detail"><span className="lv-detail-icon"><BriefcaseBusiness size={27}/></span><div className="lv-kicker"><Sparkles size={14}/> EXPERIENCE</div><h1>{exp.organization}</h1><h3>{exp.role}{exp.timeframe?' · '+exp.timeframe:''}</h3>{exp.location&&<small>{exp.location}</small>}<p>{exp.description}</p>{actions('Experience',exp)}</div>
 <div className="lv-section-header"><div><div className="lv-kicker">INSIDE THIS EXPERIENCE</div><h2>Projects at {exp.organization}</h2><p>Related work lives here, not under achievements.</p></div>{!preview&&<button className="lv-primary" onClick={()=>add('Project',exp.id)}><Plus size={16}/> Add project</button>}</div><div className="lv-grid">{filtered(data.projects.filter(p=>p.organizationId===exp.id)).map(p=>card('Project',p,'/projects/'+encodeURIComponent(p.id)))}</div>{!filtered(data.projects.filter(p=>p.organizationId===exp.id)).length&&none('No linked projects yet','Add a project to this experience to see it here.','Project',FolderKanban)}</>}
 {path==='/projects'&&<>{head('THE THINGS I BUILD','Projects','Browse projects by organization, with personal work in its own section.','Project')}{search}{data.experiences.map(e=>{const set=filtered(data.projects.filter(p=>p.organizationId===e.id));return set.length?<section key={e.id} className="lv-project-group"><div className="lv-group-title"><div><small>WORK ASSOCIATED WITH</small><h2>{e.organization}</h2></div><button className="lv-textbutton" onClick={()=>go('/experience/'+encodeURIComponent(e.id))}>Visit experience <ArrowUpRight size={17}/></button></div><div className="lv-grid">{set.map(p=>card('Project',p,'/projects/'+encodeURIComponent(p.id)))}</div></section>:null})}
 {(()=>{const set=filtered(data.projects.filter(p=>!p.organizationId||!orgById(p.organizationId)));return set.length?<section className="lv-project-group"><div className="lv-group-title"><h2>Personal & independent projects</h2></div><div className="lv-grid">{set.map(p=>card('Project',p,'/projects/'+encodeURIComponent(p.id)))}</div></section>:null})()}
 {!filtered(data.projects).length&&none('Projects belong somewhere','Add projects, and optionally connect each one to an experience.','Project',FolderKanban)}</>}
 {projectId&&project&&<><button className="lv-back" onClick={()=>go(project.organizationId?'/experience/'+encodeURIComponent(project.organizationId):'/projects')}><ArrowLeft size={17}/> {project.organizationId?'Back to experience':'All projects'}</button><div className="lv-detail"><span className="lv-detail-icon"><FolderKanban size={27}/></span><div className="lv-kicker"><Sparkles size={14}/> PROJECT</div><h1>{project.title}</h1><h3>{project.year}</h3><p>{project.description}</p>{actions('Project',project)}</div>{orgById(project.organizationId)&&<button className="lv-related" onClick={()=>go('/experience/'+encodeURIComponent(project.organizationId))}><BriefcaseBusiness size={23}/><span><small>PART OF THIS EXPERIENCE</small><strong>{orgById(project.organizationId).organization}</strong></span><ArrowRight size={19}/></button>}</>}
 {(path==='/achievements'||path==='/education')&&(()=>{const achievements=path==='/achievements',key=achievements?'achievements':'education',type=achievements?'Achievement':'Education',Icon=achievements?Trophy:GraduationCap;return <>{head(achievements?'MEANINGFUL MOMENTS':'ALWAYS LEARNING',achievements?'Achievements':'Education',achievements?'Recognition and milestones live here, separate from projects.':'Degrees, programs, courses and educational journeys.',type)}{search}<div className="lv-grid">{filtered(data[key]).map(e=>card(type,e))}</div>{!filtered(data[key]).length&&none(achievements?'A space for milestones':'Your learning journey','Add a chapter when you are ready.',type,Icon)}</>})()}
 {path==='/vault'&&<>{head('YOUR QUIET CORNER','My Vault','A dedicated place for personal records when secure storage is ready.')}<div className="lv-vault"><LockKeyhole size={32}/><h2>Keep what matters. Share what you choose.</h2><p>Private document storage, upload and permissions are planned for a future release. Please do not put sensitive information into this demo.</p><span>SECURE UPLOAD · COMING LATER</span></div><div className="lv-vault-tiles"><button onClick={()=>go('/education')}><GraduationCap/> Education <ArrowUpRight/></button><button onClick={()=>go('/achievements')}><Trophy/> Achievements <ArrowUpRight/></button></div></>}
 {!['/','/experience','/projects','/achievements','/education','/vault'].includes(path)&&!exp&&!project&&<div className="lv-empty"><h2>That chapter isn't here yet.</h2><button className="lv-primary" onClick={()=>go('/')}>Go home <ArrowRight size={16}/></button></div>}
 <footer className="lv-footer"><span>LifeVault · Every chapter matters.</span><span>Browser-only prototype · Not secure cloud storage</span></footer></main></div>
 {modal&&<div className="lv-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal('')}}><section className="lv-modal" role="dialog" aria-modal="true" aria-label="LifeVault editor"><button className="lv-close" onClick={()=>setModal('')} aria-label="Close"><X size={21}/></button>
 {modal==='entry'&&<form onSubmit={submit}><div className="lv-kicker"><Sparkles size={14}/> {editing?'EDIT ENTRY':'NEW CHAPTER'}</div><h2>{editing?'Edit this chapter':'Add something to your story'}</h2><p>Keep it simple. You can always add more later.</p><label>Category</label><select disabled={!!editing} value={form.type} onChange={e=>setForm(emptyForm(e.target.value))}>{Object.keys(typeKeys).map(x=><option key={x}>{x}</option>)}</select>
 {form.type==='Experience'?<><label>Organization or place *</label><input required value={form.organization} onChange={e=>setForm({...form,organization:e.target.value})}/><label>Role</label><input value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/><label>Timeframe</label><input value={form.timeframe} onChange={e=>setForm({...form,timeframe:e.target.value})}/><label>Location</label><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></>:<><label>{form.type==='Education'?'Program / degree':'Title'} *</label><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><label>Year</label><input value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/>{form.type==='Project'?<><label>Linked experience</label><select value={form.organizationId||''} onChange={e=>setForm({...form,organizationId:e.target.value})}><option value="">Personal / independent</option>{data.experiences.map(e=><option value={e.id} key={e.id}>{e.organization}</option>)}</select><small className="lv-hint">Linked projects appear inside that experience's page.</small></>:<><label>{form.type==='Education'?'Institution':'Awarding organization'}</label><input value={form.issuer} onChange={e=>setForm({...form,issuer:e.target.value})}/></>}</>}
 <label>Description</label><textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><label>Visibility label</label><select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})}><option>Public</option><option>Private</option></select><p className="lv-notice"><ShieldCheck size={16}/> Labels are only simulated here. This demo doesn't securely store private documents.</p><button className="lv-primary lv-submit" type="submit"><Check size={17}/> Save entry</button></form>}
 {modal==='profile'&&<form onSubmit={saveProfile}><div className="lv-kicker">MAKE IT PERSONAL</div><h2>Edit introduction</h2>{[['name','Name'],['subtitle','Short introduction'],['about','About you'],['location','Location (optional)']].map(([k,label])=><React.Fragment key={k}><label>{label}</label>{k==='about'?<textarea rows={3} value={profileDraft[k]||''} onChange={e=>setProfileDraft({...profileDraft,[k]:e.target.value})}/>:<input value={profileDraft[k]||''} onChange={e=>setProfileDraft({...profileDraft,[k]:e.target.value})}/>}</React.Fragment>)}<button className="lv-primary lv-submit" type="submit"><Check size={17}/> Save introduction</button></form>}
 {modal==='about'&&<><div className="lv-kicker">ABOUT LIFEVAULT</div><h2>A home for your whole journey</h2><p>LifeVault is organized into distinct pages. Experiences hold related projects while education and achievements stand independently. This is a local demo, not yet a multi-user service.</p><button className="lv-primary lv-submit" onClick={()=>setModal('')}>Got it <Check size={17}/></button></>}
 </section></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);