import React,{useEffect,useState} from 'react';
import {Plus,Pencil,Trash2,ArrowUpRight,BriefcaseBusiness,FolderKanban,GraduationCap,Award,FileText,ExternalLink,Eye,Download,Check,ArrowLeft,Link2} from 'lucide-react';
import './professional.css';
import AiSuggest from './ai.jsx';

const KEY='lifevault-professional-v1';
const initial={name:'',headline:'',location:'',email:'',website:'',about:'',skills:[],experience:[],projects:[],education:[],certifications:[]};
const fields={
 experience:[['title','Role or position'],['organization','Organization'],['period','Dates'],['location','Location'],['description','What did you do?']],
 projects:[['title','Project name'],['organization','Related organization (optional)'],['period','When'],['link','Project URL (optional)'],['description','What did you create?']],
 education:[['title','Degree or learning program'],['organization','School or institution'],['period','Dates'],['description','Details']],
 certifications:[['title','Certification'],['organization','Issuer'],['period','Date'],['link','Credential URL (optional)']]
};
const tabs=[['overview','Overview'],['experience','Experience'],['projects','Projects'],['skills','Skills'],['education','Education'],['certifications','Certifications'],['resume','Résumé']];
const key=()=>typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(!x||typeof x!=='object')return initial;return {...initial,...x,skills:Array.isArray(x.skills)?x.skills:[],experience:Array.isArray(x.experience)?x.experience:[],projects:Array.isArray(x.projects)?x.projects:[],education:Array.isArray(x.education)?x.education:[],certifications:Array.isArray(x.certifications)?x.certifications:[]}}catch{return initial}}
function safeLink(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:null}catch{return null}}
function Entry({item,edit,remove,readOnly=false}){return <article className="pro-entry"><div className="pro-entry-body"><div className="pro-entry-top"><h3>{item.title}</h3><span>{item.period}</span></div>{item.organization&&<strong>{item.organization}</strong>}{item.location&&<small>{item.location}</small>}{item.description&&<p>{item.description}</p>}{safeLink(item.link)&&<a href={safeLink(item.link)} target="_blank" rel="noopener noreferrer">Open link <ExternalLink size={13}/></a>}</div>{!readOnly&&<div className="pro-entry-controls"><button onClick={edit} aria-label={'Edit '+item.title}><Pencil size={16}/></button><button onClick={remove} aria-label={'Delete '+item.title}><Trash2 size={16}/></button></div>}</article>}
export default function Professional({preview=false}){
 const [data,setData]=useState(load),[tab,setTab]=useState('overview'),[editing,setEditing]=useState(null),[form,setForm]=useState({}),[mode,setMode]=useState(''),[skill,setSkill]=useState(''),[notice,setNotice]=useState(''),[readOnly,setReadOnly]=useState(false);
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(data))}catch{setNotice('Your browser storage is full. Changes may not be saved.')}},[data]);
 const set=(name,value)=>setData(x=>({...x,[name]:value}));
 const openProfile=()=>{setForm({name:data.name,headline:data.headline,location:data.location,email:data.email,website:data.website,about:data.about});setMode('profile');setEditing(null)};
 const openItem=(section,item=null)=>{setTab(section);setForm(item?{...item}:{title:'',organization:'',period:'',location:'',link:'',description:''});setEditing(item?.id||null);setMode(section)};
 const save=e=>{e.preventDefault();if(mode==='profile'){setData(x=>({...x,...form}));setMode('');setNotice('Profile saved.');return}if(!String(form.title||'').trim())return;const entry={...form,title:form.title.trim(),id:editing||key()};setData(x=>({...x,[mode]:editing?x[mode].map(y=>y.id===editing?entry:y):[entry,...x[mode]]}));setMode('');setNotice('Saved to your professional portfolio.')};
 const remove=(section,id)=>{if(!window.confirm('Remove this entry?'))return;setData(x=>({...x,[section]:x[section].filter(y=>y.id!==id)}))};
 const addSkill=e=>{e.preventDefault();const value=skill.trim();if(!value)return;if(!data.skills.some(x=>x.toLowerCase()===value.toLowerCase()))set('skills',[...data.skills,value]);setSkill('')};
 const name=data.name||'Your professional story';
 const about=data.about||'Introduce yourself in your own words. What do you care about, what do you make, and what would you like people to know?';
 const portfolio=readOnly||preview;
 const list=(section,emptyMessage)=> <div className="pro-list">{data[section].length?data[section].map(item=><Entry key={item.id} item={item} readOnly={portfolio} edit={()=>openItem(section,item)} remove={()=>remove(section,item.id)}/>):<div className="pro-empty">{emptyMessage}</div>}</div>;
 return <section className={'pro-root '+(portfolio?'pro-preview':'')}>
 <div className="pro-hero"><div className="pro-hero-content"><div className="pro-eyebrow">YOUR OPTIONAL PROFESSIONAL SPACE</div><h1>Professional</h1><p>Turn the work you've done, the skills you've learned, and the things you've created into a portfolio that feels like you.</p><div className="pro-hero-actions">{!portfolio&&<button className="primary" onClick={openProfile}><Pencil size={16}/> Edit profile</button>}<button className="pro-outline" onClick={()=>{setReadOnly(x=>!x);setTab('overview')}}><Eye size={16}/>{readOnly?'Back to editing':'Preview portfolio'}</button></div></div><div className="pro-hero-art" aria-hidden="true"><div className="pro-arch"><div className="pro-arch-circle"/><div className="pro-arch-lines"/></div><span>Build. Learn. Grow.</span></div></div>
 <nav className="pro-tabs" aria-label="Professional sections">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==='overview'&&<div className="pro-overview"><div className="pro-identity"><div className="pro-avatar">{(data.name||'Y').charAt(0).toUpperCase()}</div><h2>{name}</h2><p>{data.headline||'Your professional headline'}</p>{data.location&&<small>{data.location}</small>}{data.email&&<a href={'mailto:'+data.email}>{data.email}</a>}{safeLink(data.website)&&<a href={safeLink(data.website)} target="_blank" rel="noopener noreferrer">Personal website <ExternalLink size={13}/></a>}</div><div className="pro-about"><div className="pro-section-top"><h2>About me</h2>{!portfolio&&<button onClick={openProfile}><Pencil size={15}/> Edit</button>}</div><p>{about}</p><div className="pro-section-top"><h3>Featured skills</h3>{!portfolio&&<button onClick={()=>setTab('skills')}>Manage <ArrowUpRight size={15}/></button>}</div><div className="pro-skill-pills">{data.skills.length?data.skills.slice(0,12).map(x=><span key={x}>{x}</span>):<small>Your skills will appear here when you add them.</small>}</div></div><div className="pro-featured"><div className="pro-section-top"><h2>Selected projects</h2><button onClick={()=>setTab('projects')}>View all <ArrowUpRight size={15}/></button></div>{data.projects.length?data.projects.slice(0,3).map(item=><article key={item.id}><div className="pro-project-symbol"><FolderKanban size={21}/></div><div><strong>{item.title}</strong><p>{item.description||item.organization||'A project worth sharing.'}</p></div></article>):<div className="pro-empty">Your best work, ideas, and projects will appear here.</div>}</div></div>}
 {tab==='resume'&&<div className="pro-resume"><div className="pro-section-top"><div><div className="pro-eyebrow">A CLEAN, PRINTABLE RÉSUMÉ</div><h2>Your résumé</h2></div><button className="pro-outline" onClick={()=>window.print()}><Download size={16}/> Print / Save PDF</button></div><div className="pro-resume-sheet"><h1>{data.name||'Your Name'}</h1><p className="pro-resume-headline">{data.headline}</p><p>{[data.location,data.email,data.website].filter(Boolean).join(' · ')}</p>{data.about&&<section><h3>Profile</h3><p>{data.about}</p></section>}{data.skills.length>0&&<section><h3>Skills</h3><p>{data.skills.join(' · ')}</p></section>}{['experience','projects','education','certifications'].map(section=>data[section].length>0&&<section key={section}><h3>{section==='projects'?'Selected Projects':section.charAt(0).toUpperCase()+section.slice(1)}</h3>{data[section].map(x=><div className="pro-resume-entry" key={x.id}><strong>{x.title}</strong><span>{[x.organization,x.period].filter(Boolean).join(' · ')}</span>{x.description&&<p>{x.description}</p>}</div>)}</section>)}{!data.name&&!data.experience.length&&<p>Start by editing your professional profile and adding experiences.</p>}</div></div>}
 {tab==='skills'&&<div className="pro-section-page"><div className="pro-section-top"><div><div className="pro-eyebrow">WHAT YOU KNOW</div><h2>Skills & strengths</h2></div></div>{!portfolio&&<form className="pro-skill-form" onSubmit={addSkill}><input value={skill} onChange={e=>setSkill(e.target.value)} placeholder="Add a skill, tool, or strength" maxLength={65}/><button className="primary" type="submit"><Plus size={16}/> Add skill</button></form>}<div className="pro-skill-pills large">{data.skills.map(x=><span key={x}>{x}{!portfolio&&<button aria-label={'Remove '+x} onClick={()=>set('skills',data.skills.filter(y=>y!==x))}>×</button>}</span>)}{!data.skills.length&&<p>Add what you know. Technical, creative, and people skills all belong here.</p>}</div></div>}
 {['experience','projects','education','certifications'].includes(tab)&&<div className="pro-section-page"><div className="pro-section-top"><div><div className="pro-eyebrow">YOUR PROFESSIONAL CHAPTERS</div><h2>{tabs.find(x=>x[0]===tab)?.[1]}</h2></div>{!portfolio&&<button className="primary" onClick={()=>openItem(tab)}><Plus size={16}/> Add {tab==='experience'?'experience':'entry'}</button>}</div>{list(tab,'Nothing here yet. Add your first entry whenever you are ready.')}</div>}
 {mode&&<div className="pro-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setMode('')}}><form className="pro-modal" onSubmit={save} role="dialog" aria-modal="true" aria-label="Edit professional information"><button type="button" className="pro-close" onClick={()=>setMode('')} aria-label="Close">×</button><div className="pro-eyebrow">PROFESSIONAL · EDIT</div><h2>{mode==='profile'?'Your introduction':editing?'Edit entry':'Add an entry'}</h2>{(mode==='profile'?[['name','Full name'],['headline','Professional headline'],['location','Location'],['email','Email'],['website','Website URL'],['about','About you']]:fields[mode]).map(([key,label])=><label key={key}>{label}{['about','description'].includes(key)?<textarea rows={4} maxLength={2500} value={form[key]||''} onChange={e=>setForm(x=>({...x,[key]:e.target.value}))}/>:<input required={key==='title'} type={key==='email'?'email':key==='link'||key==='website'?'url':'text'} maxLength={240} value={form[key]||''} onChange={e=>setForm(x=>({...x,[key]:e.target.value}))}/>}</label>)}{mode==='profile'&&<AiSuggest purpose="resume" text={[form.headline,form.about].filter(Boolean).join('\n')} label="Polish professional summary" onApply={value=>setForm(x=>({...x,about:value}))}/>}
 {mode==='projects'&&<AiSuggest purpose="project" text={[form.title,form.organization,form.description].filter(Boolean).join('\n')} label="Improve project description" onApply={value=>setForm(x=>({...x,description:value}))}/>}
 {mode==='experience'&&<AiSuggest purpose="project" text={[form.title,form.organization,form.description].filter(Boolean).join('\n')} label="Improve experience description" onApply={value=>setForm(x=>({...x,description:value}))}/>}
 <button className="primary pro-save" type="submit"><Check size={16}/> Save changes</button></form></div>}
 {notice&&<div className="pro-toast" role="status">{notice}</div>}
 </section>;
}